# Generated by Skyramp v1.3.13 on 2026-03-18 19:34:00.045264432 +0000 UTC m=+260.112775533
# Command: skyramp generate contract rest http://localhost:8000/api/v1/projects/1/features/summary/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_test_feature_summary.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--path-params project_pk=1 \
# 		--provider \
# 		--response-data {"total":1,"active":1,"archived":0} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/projects/1/features/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_summary_GET_response_body = r'''{
        "active": 1,
        "archived": 0,
        "total": 1
    }'''

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v1/projects/1/features/summary/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 200
    assert skyramp.check_schema(summary_GET_response, expected_summary_GET_response_body)
    assert skyramp.get_response_value(summary_GET_response, "active") is not None
    assert skyramp.get_response_value(summary_GET_response, "archived") is not None
    assert skyramp.get_response_value(summary_GET_response, "total") is not None


if __name__ == "__main__":
    test_summary_get()
