# Generated by Skyramp v1.3.11 on 2026-03-10 01:34:38.64289953 +0000 UTC m=+222.110313913
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_duplicate_feature_error.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_create-duplicate-feature-error.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "default_enabled": false,
        "description": "Duplicate test feature",
        "name": "skyramp_dup_test_001",
        "project_id": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "default_enabled": false,
        "description": "Duplicate attempt",
        "name": "skyramp_dup_test_001",
        "project_id": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_1_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 400

if __name__ == "__main__":
    test_integration()
