# Generated by Skyramp v1.3.11 on 2026-03-09 18:18:56.795992496 +0000 UTC m=+196.726524073
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/simple/toggle/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_contract_toggle_feature_state.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--request-data {"feature_id":1,"environment_id":1,"enabled":true} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8080"

# contract test for /api/v1/features/simple/toggle/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
        "enabled": true,
        "environment_id": 1,
        "feature_id": 1
    }'''

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/simple/toggle/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_POST_response.status_code == 200

if __name__ == "__main__":
    test_endpoint_post()
