# Generated by Skyramp v1.3.11 on 2026-03-10 10:59:00.51834227 +0000 UTC m=+140.441649759
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_feature_create_list_verify.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_feature_create_list_verify.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "default_enabled": false,
        "description": "Feature for list verification test",
        "name": "list_verify_feature_5678",
        "project_id": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/list/",
        method="GET",
        query_params={"project_id": 1}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
