# Generated by Skyramp v1.3.11 on 2026-03-10 01:52:48.621911405 +0000 UTC m=+369.431624805
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_cross_project_toggle_rejection.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_cross-project-toggle-rejection.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "CrossProjTest20260310",
        "organisation": 1
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_3_POST_request_body
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201

    # Chain project_id from step 1 response
    project_id_2 = skyramp.get_response_value(endpoint_3_POST_response, "id")

    # Request Body
    endpoint_1_POST_request_body = '{{"default_enabled": false, "description": "Feature in project2 for cross-project test", "name": "cross_proj_feature_20260310", "project_id": {}}}'.format(project_id_2)
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Chain feature_id from step 2 response
    feature_id_2 = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body
    endpoint_2_POST_request_body = '{{"enabled": true, "environment_id": 1, "feature_id": {}}}'.format(feature_id_2)
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/toggle/",
        method="POST",
        body=endpoint_2_POST_request_body
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 400

if __name__ == "__main__":
    test_integration()
