# Generated by Skyramp v1.3.11 on 2026-03-09 18:18:14.688466623 +0000 UTC m=+154.618998200
# Command: skyramp generate fuzz rest http://localhost:8080/api/v1/features/simple/create/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_fuzz_create_simple_feature.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--request-data {"name":"fuzz_test_feature","description":"Fuzz test feature","project_id":1,"default_enabled":false} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8080"

# fuzz test for /api/v1/features/simple/create/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
      "name": "fuzz_test_feature",
      "description": "Fuzz test feature",
      "project_id": 1,
      "default_enabled": false
    }'''
    
    # Fuzz strategies
    endpoint_post_fuzzed_body = {
        "default_enabled": True,
        "description": "0123456789",
        "name": "0123456789",
        "project_id": -10
    }
    # Fuzz status codes
    expected_endpoint_post_status_code = {
        "default_enabled": "40x",
        "description": "40x",
        "name": "40x",
        "project_id": "40x"
    }
    # Fuzz status codes for Null values
    expected_endpoint_post_null_status_code = {
        "default_enabled": "40x",
        "description": "40x",
        "name": "40x",
        "project_id": "40x"
    }

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(endpoint_post_fuzzed_body):
        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/simple/create/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(endpoint_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_endpoint_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(endpoint_post_fuzzed_body, key) }'
        )

        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/simple/create/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_endpoint_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_post()
