# Generated by Skyramp v1.3.11 on 2026-03-10 10:43:45.062709421 +0000 UTC m=+347.803861638
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_feature_status_value_fields.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_create-feature-status-value-fields.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "default_enabled": false,
        "description": "Testing value and value_type fields",
        "name": "value_field_test_feature",
        "project_id": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Chain feature_id from step 1 response
    feature_id = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/status/",
        method="GET",
        query_params={"feature_id": feature_id, "environment_id": 1}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
