# Generated by Skyramp v1.3.11 on 2026-03-10 10:59:11.185580993 +0000 UTC m=+151.108888481
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/simple/create/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_contract_feature_create.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--request-data {"name":"contract_test_feature_9012","description":"Contract test feature","project_id":1,"default_enabled":false} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8080"

# contract test for /api/v1/features/simple/create/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
        "default_enabled": false,
        "description": "Contract test feature",
        "name": "contract_test_feature_9012",
        "project_id": 1
    }'''

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_POST_response.status_code == 201

if __name__ == "__main__":
    test_endpoint_post()
