# Generated by Skyramp v1.3.11 on 2026-03-10 02:01:29.506966975 +0000 UTC m=+280.294337372
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_create_status_toggle_verify.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_create-status-toggle-verify.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "default_enabled": false,
        "description": "Feature to verify status before and after toggle",
        "name": "toggle_verify_test_001",
        "project_id": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Chain feature_id from step 1 response
    feature_id = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/status/",
        method="GET",
        query_params={"feature_id": feature_id, "environment_id": 1}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "enabled": true,
        "environment_id": 1,
        "feature_id": 4
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/toggle/",
        method="POST",
        body=endpoint_3_POST_request_body,
        data_override={
            "environment_id": skyramp.get_response_value(endpoint_2_GET_response, "environment_id"),
            "feature_id": skyramp.get_response_value(endpoint_2_GET_response, "feature_id")
        }
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 200

    # Execute Request
    endpoint_2_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/status/",
        method="GET",
        query_params={"feature_id": feature_id, "environment_id": 1}
    )
    # Generated Assertions
    assert endpoint_2_GET_1_response.status_code == 200

if __name__ == "__main__":
    test_integration()
