# Generated by Skyramp v1.3.11 on 2026-03-10 02:01:22.406730367 +0000 UTC m=+273.194100764
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_multi_feature_list_count.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_multi-feature-list-count.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "default_enabled": false,
        "description": "Alpha feature for list count test",
        "name": "alpha_list_test_001",
        "project_id": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Chain project_id from step 1 response
    project_id = skyramp.get_response_value(endpoint_1_POST_response, "project_id")

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "default_enabled": false,
        "description": "Beta feature for list count test",
        "name": "beta_list_test_001",
        "project_id": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        data_override={"project_id": skyramp.get_response_value(endpoint_1_POST_response, "project_id")}
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/list/",
        method="GET",
        query_params={"project_id": project_id}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
