# Generated by Skyramp v1.3.11 on 2026-03-10 02:01:24.907798365 +0000 UTC m=+275.695168752
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_project_status_after_toggle.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_project-status-after-toggle.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "default_enabled": false,
        "description": "Feature to test project-wide status after toggle",
        "name": "proj_status_toggle_001",
        "project_id": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Chain feature_id and project_id from step 1 response
    feature_id = skyramp.get_response_value(endpoint_1_POST_response, "id")
    project_id = skyramp.get_response_value(endpoint_1_POST_response, "project_id")

    # Request Body
    endpoint_3_POST_request_body = '{{"enabled": true, "environment_id": 1, "feature_id": {}}}'.format(feature_id)

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/toggle/",
        method="POST",
        body=endpoint_3_POST_request_body
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/status/",
        method="GET",
        query_params={"project_id": project_id}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
