# Generated by Skyramp v1.3.11 on 2026-03-10 01:52:48.895165834 +0000 UTC m=+369.704879244
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_default_enabled_project_wide_disable.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_default-enabled-project-wide-then-disable.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "default_enabled": true,
        "description": "Project-wide status test with default_enabled=true",
        "name": "skyramp_proj_wide_20260310",
        "project_id": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/create/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Chain feature_id from step 1 response
    feature_id = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/status/",
        method="GET",
        query_params={"project_id": 1}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

    # Request Body
    endpoint_3_POST_request_body = '{{"enabled": false, "environment_id": 1, "feature_id": {}}}'.format(feature_id)

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/toggle/",
        method="POST",
        body=endpoint_3_POST_request_body
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 200

    # Execute Request
    endpoint_2_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/simple/status/",
        method="GET",
        query_params={"project_id": 1}
    )
    # Generated Assertions
    assert endpoint_2_GET_1_response.status_code == 200

if __name__ == "__main__":
    test_integration()
