# Generated by Skyramp v1.3.11 on 2026-03-09 19:01:33.8639071 +0000 UTC m=+125.759589264
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/simple/list/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_contract_list_simple_features.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--query-params project_id=1 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /api/v1/features/simple/list/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/features/simple/list/",
        method="GET",
        headers=headers,
        query_params={"project_id": "1"}
    )

    # Generated Assertions
    assert skyramp.check_status_code(endpoint_GET_response, "20x")

if __name__ == "__main__":
    test_endpoint_get()
