# Generated by Skyramp v1.3.11 on 2026-03-10 01:34:38.827482637 +0000 UTC m=+222.294897020
# Command: skyramp generate fuzz rest http://localhost:8080/api/v1/features/simple/status/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_fuzz_get_feature_status.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--query-params feature_id=1,environment_id=1" \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8080"

# fuzz test for /api/v1/features/simple/status/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Fuzz strategies
    endpoint_get_fuzzed_query = {
        "environment_id": "1\"",
        "feature_id": "1"
    }
    # Fuzz status codes
    expected_endpoint_get_fuzzed_query_status_code = {
        "environment_id": "40x",
        "feature_id": "40x"
    }

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/features/simple/status/",
        method="GET",
        headers=headers,
        query_params={
            "environment_id": "1\"",
            "feature_id": "1"
        },
        expected_code="20x"
    )

    for key in endpoint_get_fuzzed_query:
        query_params = {
            "environment_id": "1\"",
            "feature_id": "1"
        }

        query_params[key] = endpoint_get_fuzzed_query[key]

        # Execute Request
        endpoint_GET_response = client.send_request(
            url=URL,
            path="/api/v1/features/simple/status/",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_endpoint_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to { endpoint_get_fuzzed_query[key] }'
        )

        query_params = {
            "environment_id": "1\"",
            "feature_id": "1"
        }

        query_params[key] = ""

        # Execute Request
        endpoint_GET_response = client.send_request(
            url=URL,
            path="/api/v1/features/simple/status/",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_endpoint_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to ""'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_get()
