# Generated by Skyramp v1.3.11 on 2026-03-09 19:01:34.065085136 +0000 UTC m=+125.960767270
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/features/simple/toggle/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_fuzz_toggle_feature_state.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--request-data {"feature_id":1,"environment_id":1,"enabled":true} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8080"

# fuzz test for /api/v1/features/simple/toggle/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
      "feature_id": 1,
      "environment_id": 1,
      "enabled": true
    }'''
    
    # Fuzz strategies
    endpoint_post_fuzzed_body = {
        "enabled": True,
        "environment_id": -10,
        "feature_id": -10
    }
    # Fuzz status codes
    expected_endpoint_post_status_code = {
        "enabled": "40x",
        "environment_id": "40x",
        "feature_id": "40x"
    }
    # Fuzz status codes for Null values
    expected_endpoint_post_null_status_code = {
        "enabled": "40x",
        "environment_id": "40x",
        "feature_id": "40x"
    }

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/simple/toggle/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(endpoint_post_fuzzed_body):
        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/simple/toggle/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(endpoint_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_endpoint_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(endpoint_post_fuzzed_body, key) }'
        )

        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/simple/toggle/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_endpoint_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_post()
